replicaCount: 1

image:
  repository: ghcr.io/cloud-design-patterns-journey/inv-bff-bbl
  tag: main
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

backend:
  url: http://inv-svc:8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
