replicaCount: 1

image:
  repository: ghcr.io/cloud-design-patterns-journey/inv-bff-bbl
  tag: main
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

backend:
  url: http://inv-bff-bbl:3000

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
